#include <mysql/mysql.h>
#include <iostream>
#include <stdlib.h>
#include <time.h>
#include "../../CLogging.h"


#define P_DIR_IN 1
#define P_DIR_OUT 2
#define P_DIR_INOUT 3

#define P_TYPE_INT 1
#define P_TYPE_VARCHAR 2
#define P_TYPE_FLOAT 3
#define P_TYPE_TEXT 4
#define P_TYPE_TIMESTAMP 5


using namespace std; 
    
class CNHDBAccess
{
  public:   
    CNHDBAccess(string server, string username, string password, string database, CLogging *log);
    ~CNHDBAccess();
    int dbConnect();
    void dbDisconnect();
    int exec_sp (string sp_name, int param_dir[], int param_type[], void **param_value, int param_length[], int param_count);
    void time_t2mysql(MYSQL_TIME *myTime, const time_t *cTime);
    
// {AUTOGENERATED-SP-DEFINITIONS}
    
  private:
      string server;
      string username;
      string password;
      string database;
      MYSQL mysql;
      MYSQL_RES *result; 
      CLogging *log;
      bool connected;
      pthread_mutex_t mysql_mutex;
};