-- Create user
GRANT USAGE ON *.* TO 'gk'@'%';
DROP USER 'gk'@'%';
CREATE USER 'gk'@'%' IDENTIFIED BY 'gk';
GRANT USAGE ON * . * TO 'gk'@'%' IDENTIFIED BY 'gk' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT SELECT ,
EXECUTE ON * . *
TO 'gk'@'%'
WITH MAX_QUERIES_PER_HOUR 0
MAX_CONNECTIONS_PER_HOUR 0
MAX_UPDATES_PER_HOUR 0